services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo-volume:/data/db
  web:
    image: auditize
    ports:
      - "8001:80"
    environment:
        - AUDITIZE_MONGODB_URI=mongodb://root:root@mongo:27017/
        - AUDITIZE_JWT_SIGNING_KEY=${AUDITIZE_JWT_SIGNING_KEY}
        - AUDITIZE_CORS_ALLOW_ORIGINS=${AUDITIZE_CORS_ALLOW_ORIGINS}
        - AUDITIZE_CORS_ALLOW_CREDENTIALS=${AUDITIZE_CORS_ALLOW_CREDENTIALS}
        - AUDITIZE_CORS_ALLOW_METHODS=${AUDITIZE_CORS_ALLOW_METHODS}
        - AUDITIZE_CORS_ALLOW_HEADERS=${AUDITIZE_CORS_ALLOW_HEADERS}
volumes:
    mongo-volume:
