services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo-data:/data/db
    ports:
      - "27018:27017" # for debugging purposes
  web:
    image: auditize
    entrypoint:
      [
        "sh",
        "-c",
        "python -m auditize bootstrap-default-superadmin && python -m auditize serve --host 0.0.0.0 --port 8000",
      ]
    ports:
      - "8001:8000"
    env_file: ".env"
    environment:
      - AUDITIZE_MONGODB_URI=mongodb://root:root@mongo:27017/
  scheduler:
    image: auditize
    command: ["schedule"]
    env_file: ".env"
    environment:
      - AUDITIZE_MONGODB_URI=mongodb://root:root@mongo:27017/
      # we set PYTHONUNBUFFERED, otherwise the print() from "schedule" are not shown
      - PYTHONUNBUFFERED=1
volumes:
  mongo-data:
