name: auditize

x-auditize-variables: &auditize-variables
  AUDITIZE_PG_HOST: postgres
  AUDITIZE_PG_USER: auditize
  AUDITIZE_PG_PASSWORD: auditize
  AUDITIZE_ES_URL: http://elastic:9200

services:
  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: auditize
      POSTGRES_PASSWORD: auditize
      POSTGRES_DB: auditize
    volumes:
      - pgdata:/var/lib/postgresql/data
  elastic:
    image: elasticsearch:8.19.4
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - esdata:/usr/share/elasticsearch/data
  web:
    image: auditize
    depends_on:
      - postgres
      - elastic
    command: ["serve", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8080:8000"
    env_file: ".env"
    environment:
      <<: *auditize-variables
  scheduler:
    image: auditize
    depends_on:
      - postgres
      - elastic
    command: ["schedule"]
    env_file: ".env"
    environment:
      <<: *auditize-variables
      # we set PYTHONUNBUFFERED, otherwise the print() from "schedule" are not shown
      PYTHONUNBUFFERED: 1
volumes:
  pgdata:
  esdata: