services:
  mongo:
    image: mongo
    hostname: mongo # we need a static hostname for MongoDB replication
    command: ["--replSet", "rs0"]
    # Initialization of the replica set is needed the very first time:
    # docker exec -it auditize-mongo-1 mongosh --eval "rs.initiate()"
    restart: always
    volumes:
      - mongo-data:/data/db
    ports:
      - "27018:27017" # for debugging purposes
  web:
    image: auditize
    depends_on:
      - mongo
    command: ["serve", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8080:8000"
    env_file: ".env"
    environment:
      - AUDITIZE_MONGODB_URI=mongodb://mongo:27017/
  scheduler:
    image: auditize
    depends_on:
      - mongo
    command: ["schedule"]
    env_file: ".env"
    environment:
      - AUDITIZE_MONGODB_URI=mongodb://mongo:27017/
      # we set PYTHONUNBUFFERED, otherwise the print() from "schedule" are not shown
      - PYTHONUNBUFFERED=1
volumes:
  mongo-data:
