services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo-data:/data/db
    ports:
      - "27018:27017" # for debugging purposes
  web:
    image: auditize/web
    ports:
      - "8001:80"
    env_file: ".env"
    environment:
      - AUDITIZE_MONGODB_URI=mongodb://root:root@mongo:27017/
  tasks:
    image: auditize/tasks
    env_file: ".env"
    environment:
      - AUDITIZE_MONGODB_URI=mongodb://root:root@mongo:27017/
volumes:
  mongo-data:
