services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo-data:/data/db
    ports:
      - "27018:27017" # for debugging purposes
  web:
    image: auditize
    depends_on:
      - mongo
    command: ["serve", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8080:8000"
    env_file: ".env"
    environment:
      - AUDITIZE_MONGODB_URI=mongodb://root:root@mongo:27017/
  scheduler:
    image: auditize
    depends_on:
      - mongo
    command: ["schedule"]
    env_file: ".env"
    environment:
      - AUDITIZE_MONGODB_URI=mongodb://root:root@mongo:27017/
      # we set PYTHONUNBUFFERED, otherwise the print() from "schedule" are not shown
      - PYTHONUNBUFFERED=1
volumes:
  mongo-data:
