site_name: Auditize
site_url: https://auditize.org
nav:
  - Home: index.md
  - Concepts: overview.md
  - Configuration: config.md
  - Log data model: logs.md
  - Sending logs: sending-logs.md
  - Web Component: web-component.md
  - REST API: api.html
theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/favicon.png
  features:
    - content.code.copy
    - toc.integrate
  font: false
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - tables
plugins:
  - glightbox:
      touchNavigation: false
      zoomable: false
