site_name: Auditize
site_url: https://auditize.org
nav:
  - Home: index.md
  - Overview: overview.md
  - Installation: install.md
  - Configuration: config.md
  - Log data model: log-data-model.md
  - Sending logs: sending-logs.md
  - Web Component: web-component.md
  - REST API: api.html
theme:
  name: material
  logo: images/logo.svg
  favicon: images/favicon.png
  features:
    - content.code.copy
    - toc.integrate
  font: false
extra_css:
  - css/custom.css
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - tables
